name: Conditional CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Conditional Step
        run: |
          echo "This step runs only when on the main branch and the commit message contains 'release'."
   
